spring:
  application:
    name: Event-Management



  datasource:
    url: jdbc:mysql://localhost:3306/eventmanagment
    username: root
    password: Inal@014!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
    SECRET_KEY: XGpWtkxHVTPBA9MBWvYkmBiJW5ZolJ2Rsupersecurekey123
    EXPIRATION_TIME: 86400000